[package]
name = "rsdb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
derive_more = { version = "1.0.0", features = ["debug"] }
fallible-iterator = "0.3.0"
gimli = "0.31.1"
goblin = "0.9.2"
memmap2 = "0.9.5"
object = "0.36.7"
scroll = "0.12.0"
